<?php
$pageTitle = 'BMC Home';
$bodyClass = 'page-home';
include 'php-inc/head.php';
?>

<section class="layout-full-bleed">
	<div class="layout-inner-wrap">

		<h1>BMC Software Cookie Notice </h1>

	</div>
	<div class="layout-inner-wrap divider-large">
		<section class="layout-primary">

			<section>
				<p>
					BMC Software uses cookies on its website.&nbsp; You can find out more about cookies and how to control them in the information below.
				</p>
				<p>
					By using <a href="/legal/cookie-notice.html?abc=cXzmhTcG#bmcwebsite">BMC website</a>, you accept the use of cookies in accordance with this Cookie Notice.
				</p>
				<p>
					If you do not accept the use of cookies please disable them following the instructions in this Cookie Notice, by using the <a href="http://info.evidon.com/pub_info/2841?v=1&amp;nt=1&amp;nw=true">Cookie Consent Tool</a> or by changing your browser settings so that cookies from this website cannot be placed on your computer or mobile device.
				</p>
				<p>
					<b>What is a cookie?</b>
				</p>
				<p>
					Cookies are a small amount of data generated by a website and   downloaded to your computer or mobile device when you visit a website.   Such cookies are sent back to the originating website on each subsequent   visit, or to any other visited website that recognizes that cookie.   Cookies are useful because they allow a website to recognize a user&rsquo;s   device.
				</p>
				<p>
					Cookies do lots of different jobs. The most common use is to store a   user&rsquo;s login information at a specific site, e.g., username and  password  after the user clicks on "Remember me on this computer," which   generates a login cookie. Some cookies are used by e-commerce sites to   store items placed in a shopping cart. Other cookies allow you  navigate  between pages efficiently, remembering your preferences and  search  settings, and generally improving your user experience, such as   remembering recently-viewed stock quotes.&nbsp; Many cookies collect   information about how visitors use a website, for instance which pages   visitors go to most often. They also help ensure that online   advertisements are more relevant to a user of a website and the user&rsquo;s   interests by creating the user&rsquo;s profile which is later used to send ad   messages in line with the preferences shown by the user during   navigation of the web.
				</p>
				<p>
					For further information on cookies, including how to see what cookies   have been set on your device and how to manage and delete them, visit <a href="http://www.allaboutcookies.org/">http://www.allaboutcookies.org/</a>.
				</p>
				<p>
					<b>What cookies do we use on </b><b><a href="/legal/cookie-notice.html?abc=cXzmhTcG#bmcwebsite">BMC website</a>?</b>
				</p>
				<p>
					The types of cookies used on this website can be classified into one   of four categories, namely Essential Cookies, Analytics Cookies,   Customization Cookies and Advertising Cookies.
				</p>
			</section>

			<!-- BEGIN HTML AREA 1 -->

	
			
			<!--<![endif]-->
			<p>
				<b>1.&nbsp; Essential Cookies.</b>&nbsp; These cookies are essential  in order to enable you to move around the website and use its features,  such as accessing secure areas of the website. This category of cookies  cannot be disabled. We may use the following Essential Cookies:
			</p>
			<table class="responsive-table-legal">
				<thead>
					<tr >
						<td ><b>Cookie Name</b></td>
						<td ><b>Source</b></td>
						<td ><b>Expiry (Days)</b></td>
						<td ><b>Purpose</b></td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Akamai Technologies</td>
						<td>01AI</td>
						<td>365</td>
						<td>Enables analytics provider, data aggregator/supplier, data management platform</td>
					</tr>
					<tr>
						<td>BMC Software</td>
						<td>BMC Software</td>
						<td>Non-Expiry</td>
						<td>Enables content management/web system and tracking</td>
					</tr>
					<tr>
						<td>Limelight Networks Dynamic Site Platform (formerly Clickability)</td>
						<td>Clickability Beacon, Id, vid, JSESSIONID, Stats_Session</td>
						<td>Non-Expiry, 24,855, 24,855, Non-Expiry, Non-Expiry</td>
						<td>Enables content management/web system and tracking</td>
					</tr>
					<tr>
						<td>Perceptive Software (formerly Twistage)</td>
						<td>Perceptive</td>
						<td>Non-Expiry</td>
						<td>Enables videos</td>
					</tr>
				</tbody>
			</table>

			<!-- END HTML AREA 1 -->

			<!-- BEGIN HTML AREA 2 -->

			<br />
			&nbsp;
			<br />
			<p>
				<b>2.&nbsp; Analytics Cookies.</b>&nbsp; These cookies collect  information about how you use a website, for instance which pages you go  to most often, what searches you perform, and whether you receive error  messages from the visited web pages. These cookies are associated to  your web browser and may be linked to any personal information we may  have about you.
			</p>
			<p>
				Our website uses Google Analytics Cookies. Information collected by  the Google Analytics cookies will be transmitted to and stored by Google  on servers in the United States of America and anywhere else they may  be located in accordance with its privacy practices. To see an overview  of privacy at Google and how this applies to Google Analytics, visit <a href="http://www.google.co.uk/intl/en/analytics/privacyoverview.html">http://www.google.co.uk/intl/en/analytics/privacyoverview.html</a>. You may opt out of Google Analytics&rsquo; tracking by visiting <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a>. Our website may use the following Google Analytics Cookies and other Analytic Cookies:
			</p>
			<table class="responsive-table-legal">
				<thead>
					<tr >
						<td ><b>Cookie Name</b></td>
						<td ><b>Source</b></td>
						<td ><b>Expiry (Days)</b></td>
						<td ><b>Purpose</b></td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Adobe Marketing Cloud (Analytics)</td>
						<td>Omniture (Adobe Analytics), Adobe Tag Conatiner, s_vi</td>
						<td>Non-Expiry, Non-Expiry, 730</td>
						<td>Enables analytics provider, tag manager, tracker, widget</td>
					</tr>
					<tr>
						<td>Crazy Egg</td>
						<td>Crazy Egg</td>
						<td>Non-Expiry</td>
						<td>Enables analytics</td>
					</tr>
					<tr>
						<td>Google Analytics</td>
						<td>Google Analytics, __utma, __utmb, __utmc, __utmv, __utmz</td>
						<td>Non-Expiry, 730, 0, Non-Expiry, 0, 183</td>
						<td>Enables analytics</td>
					</tr>
				</tbody>
			</table>
			<br />
			&nbsp;
			<br />

			<!-- END HTML AREA 2 -->

			<!-- BEGIN HTML AREA 3 -->

			<p>
				<b>3. Customization Cookies.</b> Among other things noted in  the table below, these are used to recognize you when you return to our  website, enable web widgets to work correctly, and may collect  additional information about you. This enables us to personalize our  content for you, greet you by name and remember your preferences (for  example, your choice of language or region). Our website may use the  following Customization Cookies:
			</p>
			<table class="responsive-table-legal"> 
				<thead>
					<tr >
						<td ><b>Cookie Name</b></td>
						<td ><b>Source</b></td>
						<td ><b>Expiry (Days)</b></td>
						<td ><b>Purpose</b></td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>AddThis</td>
						<td>AddThis, __atuvc, bt, bt2, di2, dt, loc, uid, uit, um</td>
						<td>Non-Expiry, Non-Expiry, 730</td>
						<td>Enables analytics provider, data aggregator/supplier, social media, widget</td>
					</tr>
					<tr>
						<td>Adobe Marketing Cloud (Target)</td>
						<td>Adobe Test &amp; Target</td>
						<td>Non-Expiry</td>
						<td>Enables creative/ad format technology, tracker</td>
					</tr>
					<tr>
						<td>BlueKai</td>
						<td>BlueKai, bkc, bkdc, bklc, bko, bku, bkw5</td>
						<td>Non-Expiry, 180, 180, 180, 180, 180, 180</td>
						<td>Enables data aggregator/supplier, data management platform, tracker</td>
					</tr>
					<tr>
						<td>Demandbase</td>
						<td>Demandbase</td>
						<td>Non-Expiry</td>
						<td>Enables tracker, analytics provider, data management platform</td>
					</tr>
					<tr>
						<td>Eloqua (Oracle Marketing Cloud)</td>
						<td>&nbsp;</td>
						<td>Non-Expiry</td>
						<td>Enables social media, widget</td>
					</tr>
					<tr>
						<td>Facebook Connect</td>
						<td>Facebook Connect</td>
						<td>Non-Expiry</td>
						<td>Enables social media, widget</td>
					</tr>
					<tr>
						<td>Facebook Social Plugins</td>
						<td>Facebook Social Plugins</td>
						<td>Non-Expiry</td>
						<td>Enables social media, widget</td>
					</tr>
					<tr>
						<td>Full Circle Studies</td>
						<td>ScoreCard Research Beacon, UID, UIDR,</td>
						<td>Non-Expiry, 720, 720</td>
						<td>Enables business intelligence, tracker</td>
					</tr>
					<tr>
						<td>Google</td>
						<td>NID</td>
						<td>183</td>
						<td>Enables ad network, analytics provider, publisher, mobile, widget, ad, tracker</td>
					</tr>
					<tr>
						<td>Google Plus</td>
						<td>Google Plus</td>
						<td>Non-Expiry</td>
						<td>Enables social media, widget</td>
					</tr>
					<tr>
						<td>LivePerson</td>
						<td>LivePerson</td>
						<td>Non-Expiry</td>
						<td>Enables widget, analytics, live chat</td>
					</tr>
					<tr>
						<td>ShareThis</td>
						<td>ShareThis</td>
						<td>Non-Expiry</td>
						<td>Enables social media, widget</td>
					</tr>
					<tr>
						<td>YouTube</td>
						<td>YouTube</td>
						<td>Non-Expiry</td>
						<td>Enables video, widget</td>
					</tr>
				</tbody>
			</table>

			<!-- END HTML AREA 3 -->

			<!-- BEGIN HTML AREA 4 -->

			<br />
			&nbsp;
			<br />
			<p>
				<b>4. Advertising Cookies.</b> These cookies record your visit  to our website, the pages you have visited, and the links you have  followed. We will use this information to make our website and the  advertising displayed on it more relevant to your interests. We may also  share this information with third parties for this purpose. Our website  may use the following Advertising Cookies.
			</p>
			<table class="responsive-table-legal">
				<thead>
					<tr >
						<td ><b>Cookie Name</b></td>
						<td ><b>Source</b></td>
						<td ><b>Expiry (Days)</b></td>
						<td ><b>Purpose</b></td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>[x+1] xplusone</td>
						<td>[x+1], SEQUI_JRNL, X1ID, TMP_X1ID</td>
						<td>Non-Expiry, 549, 549, Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>AppNexus</td>
						<td>AppNexus, anj, sess, uuid2</td>
						<td>Non-Expiry, 90, 1, 90</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Bizo</td>
						<td>Bizo, BizoCusomSegments, BizoData, BizoID, BizoUserMatchHistory</td>
						<td>Non-Expiry, Non-Expiry, Non-Expiry, 730</td>
						<td>&nbsp;Enables tracker,ad network, data aggregator/supplier</td>
					</tr>
					<tr>
						<td>DoubleClick</td>
						<td>DoubleClick, DoubleClick Spotlight, DoubleClick Floodlight, id</td>
						<td>Non-Expiry, Non-Expiry, Non-Expiry, 730</td>
						<td>&nbsp;Enables ad, tracker</td>
					</tr>
					<tr>
						<td>Dstillery (formerly Media6Degrees)</td>
						<td>Media6Degrees, acs, cckz, clid, ipinfo</td>
						<td>Non-Expiry, 180, 180, 180, 180</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Facebook Exchange (FBX)</td>
						<td>Facebook Exchange (FBX)</td>
						<td>Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Google AdWords</td>
						<td>Google AdWords Conversion</td>
						<td>Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>MediaMath</td>
						<td>Adroit Digital Solutions, MediaMath, HRL*, mt_misc, mt_mop, uuid</td>
						<td>Non-Expiry, Non-Expiry, 28, 30, 30, 365</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Resonate Insights</td>
						<td>Resonate Networks, RCID, RCOUNT</td>
						<td>Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Right Media</td>
						<td>Right Media</td>
						<td>Non-Expiry</td>
						<td>Enables ad</td>
					</tr>
					<tr>
						<td>Rubicon Project</td>
						<td>Rubicon, put_1512, rpb, rpx</td>
						<td>Non-Expiry, 30, 30, 30</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Simpli.fi</td>
						<td>Simpli.fi, uid</td>
						<td>Non-Expiry, 366</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Tapad</td>
						<td>Tapad</td>
						<td>Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
					<tr>
						<td>Turn</td>
						<td>Turn</td>
						<td>Non-Expiry</td>
						<td>&nbsp;Enables ad</td>
					</tr>
				</tbody>
			</table>

			<!-- END HTML AREA 4 -->

			<section>
				<p>
					You may control and delete any of the above-listed cookies by using the <a href="http://info.evidon.com/pub_info/2841?v=1&amp;nt=1&amp;nw=true">Cookie Consent Tool</a> or through your browser settings as described below.
					<br />
					<br />
					<b>How to control and delete cookies through the browser</b>
					<br />
					<br />
					The ability to enable, disable, or delete cookies can be completed at   browser level. In order to do this, follow the instructions provided by   your browser (usually located within the &ldquo;Help&rdquo;, &ldquo;Tools&rdquo; or &ldquo;Edit&rdquo;   facility).&nbsp; Disabling a cookie or category of cookie does not delete the   cookie from your browser; you will need to do this yourself from  within  your browser.
					<br />
					<br />
					<b>Cookies that have been set in the past</b>
					<br />
					<br />
					If you have disabled one or more cookies, we may still use information   collected from cookies prior to your disabled preference being set,   however, we will stop using the disabled cookie to collect any further   information.
				</p>
				<p>
					To remove all known information about you from BMC systems, please email <a href="mailto:privacy@bmc.com">privacy@bmc.com</a>.
					<br />
					<br />
					<b>Third Parties Cookies</b>
					<br />
					<br />
					Please note that third parties (including, for example, advertising   networks and providers of external services like web traffic analysis   services) may also use cookies over which we have no control. These   cookies are likely to be analytical, performance cookies, or targeting   cookies
				</p>
				<p>
					You block cookies by activating the setting on your browser that   allows you to refuse the setting of all or some cookies. However, if you   use your browser settings to block all cookies (including essential   cookies) you may not be able to access our website at all or certain   parts of it.
				</p>
				<p id="bmcwebsite">
					<b>BMC Websites:</b>
				</p>
				<p>
					http://www.bmc.com/
				</p>
				<p>
					http://www.bmc.com/en-AU/
				</p>
				<p>
					http://www.bmc.com/en-BE/
				</p>
				<p>
					http://www.bmc.com/en-CA/
				</p>
				<p>
					http://www.bmc.com/en-CY/
				</p>
				<p>
					http://www.bmc.com/el-GR/
				</p>
				<p>
					http://www.bmc.com/en-HK/
				</p>
				<p>
					http://www.bmc.com/en-IN/
				</p>
				<p>
					http://www.bmc.com/en-ME/
				</p>
				<p>
					http://www.bmc.com/nordic/
				</p>
				<p>
					http://www.bmc.com/pl-PL/
				</p>
				<p>
					http://www.bmc.com/en-ZA/
				</p>
				<p>
					http://www.bmc.com/en-SG/
				</p>
				<p>
					http://www.bmc.com/zh-TW/
				</p>
				<p>
					http://www.bmc.com/tr-TR/contacts-locations/
				</p>
				<p>
					http://www.bmc.com/en-GB/
				</p>
				<p>
					http://www.bmcbrandmark.com/
				</p>
				<p>
					http://itsm.bmcassessments.com
				</p>
				<p>
					http://www.jobschedulingassessment.com
				</p>
				<p>
					http://www.mainframemonitor.com/
				</p>
				<p>
					http://www.cloud-assessment-tool.com/
				</p>
				<p>
					http://mlc.bmcassessments.com
				</p>
				<p>
					https://www.bladelogic.com/support/supportLogin.jsp
				</p>
				<p>
					https://webapps.bmc.com/signon/content/logon.jsp
				</p>
				<p>
					http://discovery.bmc.com/
				</p>
				<p>
					https://www.bmclogostore.com/
				</p>
				<p>
					http://support.numarasoftware.com/
				</p>
				<p>
					https://support.coradiant.com/
				</p>
				<p>
					https://magickb.remedy.com/helpdesk
				</p>
				<p>
					http://developer.bmc.com/ar/apply-ta.jsp
				</p>
				<p>
					https://communities.bmc.com
				</p>
				<p>
					http://www.trackit.com
				</p>
				<p>
					http://try.onbmc.com
				</p>
				<p>
					<b>Cookie Notice Rev. 2014-07-11</b>
				</p>
			</section>

		</section>
		<aside class="layout-secondary">

			<section class="float-rail-nav-container">
				<h3>Legal Resources</h3>
				<ol class="float-rail-nav ">

					<li >
						<a  class="learn-more"  href="/legal/legal-index.html"  target="_self" >Legal</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/terms-of-use.html"  target="_self" >Terms of Use</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/trademarks.html"  target="_self" >Trademarks</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/technical-disclosures.html"  target="_self" >Technical Disclosures</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/data-privacy-binding-corporate-rules.html"  target="_self" >Data Privacy Binding Corporate Rules (BCR)</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/privacy-policy.html"  target="_self" >Privacy Policy</a>
					</li>

					<li  class="current" >
						<a  class="current learn-more"  href="/legal/cookie-notice.html"  target="_self" >Cookie Notice</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/anti-piracy.html"  target="_self" >Anti-Piracy/License Non-Compliance</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/country-specific-disclosures.html"  target="_self" >Country-Specific Disclosures</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/agreements.html"  target="_self" >Agreements</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/code-of-conduct.html"  target="_self" >Code of Conduct</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/export-compliance.html"  target="_self" >Export Compliance</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/ethics-helpline.html"  target="_self" >Ethics HelpLine</a>
					</li>

					<li >
						<a  class="learn-more"  href="/legal/equal-employment-opportunity.html"  target="_self" >Equal Employment Opportunity Policy</a>
					</li>
				</ol>
			</section>

		</aside>
	</div><!-- / layout-inner-wrap -->
</section>

<?php
include 'php-inc/foot.php';
?>