<?php
$pageTitle = 'BMC Home';
$bodyClass = 'home page-home';
include 'php-inc/head.php';
?>

<section class="wallpapered bar" data-wallpaper-options='{"source":"http://media.cms.bmc.com/images/it-operations-service.jpg"}'>
	<div class="offset-wrapper">
		<div class="layout-inner-wrap">
			<div class="offset-hero-medium banner -ribbon">
				<div class="offset-hero-medium-inner-wrap">
					<h1>IT Operations Analytics (ITOA)</h1>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="layout-full-bleed">
	<div class="layout-inner-wrap">
		<article class="layout-primary">

			<section class="fortune-500-bg-product bg-white">
				<div class="flex flex-center flex-wrap js-eh py2">
					<div class="flex-item lg-col-5 md-col-5 sm-col-12">
						<p class="h2-legacy">
							<strong>BMC digital IT powers 82% of Fortune 500 companies</strong>
						</p>
					</div>
					<div class="flex-item lg-col-7 md-col-7 sm-col-12">
						<img src="http://media.cms.bmc.com/designimages/fortune-500-bg-product-july-2016.png" alt="" title="">
					</div>
				</div>
			</section>

			<section>
				<h2>What is IT Operations Analytics?</h2>
				<p>
					IT Operations Analytics (ITOA) automates the process of collecting, organizing, and identifying patterns in highly distributed, diverse and fast-changing service and application data to identify problems faster and improve IT system performance.
				</p>
				<img class="layout-right width-xs ml3em" src="http://media.cms.bmc.com/images/it-operations-analytics.png" alt="IT Operations Analytics" />

				<p>
					The modern digital business revolution infuses technology in every step of an organization&rsquo;s value chain. This unprecedented use of technology creates a complex challenge for IT Infrastructure and Operations organizations, as it becomes difficult to collect and organize the explosion of data generated by new digital business systems and sources.
				</p>
				<p>
					Operational analytics gives IT Operations Management (ITOM) teams the right information, at the right time. It allows them to quickly focus their efforts, reduce the time it takes to solve problems, proactively identify issues and optimize system and application performance to support business needs.
				</p>
			</section>

			<figure>
				<h2>Video: TrueSight Intelligence makes sense of your data</h2>
				<p>
					Get fast, accurate analytics that create insight at the intersection of data and the digital business. (1:54)
				</p>
				<div id="youtube_ZEtgvukrZfA" class="youtube-video inline-youtube-video-player">
					<div id="ZEtgvukrZfA" class="youtubePlayer" data-src="ZEtgvukrZfA" data-autoplay=0 data-fullscreen=0></div>
					<p id="youtubeOverlay_ZEtgvukrZfA" class="youtubeOverlay">
						Find out how BMC can help you. <a id='overlayLink' href='http://www.bmc.com/forms/ESM_ContactCenter_ContactRequest_BMCcom_EN_Jan2014.html'>Contact a sales rep ›</a>
					</p>
				</div>
			</figure>

			<section>
				<h2>Fast, data-driven action with ITOA</h2>
				<p>
					In today&rsquo;s digital business, data is the currency that guides and drives all decisions and actions. Breaking down IT information silos and automatically organizing multi-structured data from diverse, dynamic sources, operational analytics software solutions transform disconnected data points, which lack meaning, into actionable information.
				</p>
				<p>
					IT Operations Analytics should be applied to the modern IT Infrastructure and Operations environment to:
				</p>
				<ul>
					<li>
						Troubleshoot and anticipate problems in the application and service infrastructure through analytics integrated with existing IT Operations Management tools and practices
					</li>
					<li>
						Optimize overall IT service performance and guide business decisions through a single analytics platform that contextualizes data from distributed systems through the business
					</li>
				</ul>
			</section>

			<section>
				<h2>Troubleshooting and problem identification </h2>
				<p>
					<a href="/it-solutions/truesight-it-data-analytics.html">TrueSight IT Data Analytics</a> allows you to proactively identify and  detect troublesome patterns on an ongoing basis and create alerts and  reports to take action before  your users are affected. With TrueSight's integrated IT analytics software you'll get better IT insight &ndash; right out of the box.
				</p>
				<ul>
					<li>
						Collect, index, and monitor logs and events for abnormalities
					</li>
					<li>
						Perform ad-hoc searches of all log data across the entire IT environment from a single console
					</li>
					<li>
						Correlate log data with events and service models, or application groups
					</li>
				</ul>
				<p>
					As a result, empowered ITOM teams can:
				</p>
				<ul>
					<li>
						Detect, prioritize, diagnose, and resolve service issues more quickly than ever before
					</li>
					<li>
						Save successful prior resolutions and automate notifications for the fast resolution of common issues
					</li>
					<li>
						Integrate event management, and log and machine data analytics for a holistic view of the entire data center
					</li>
				</ul>
			</section>

			<section>
				<a class="btn" href="/it-solutions/truesight-it-data-analytics.html"  target="_self">Explore IT Data Analytics&nbsp;&#8250;</a>
			</section>

			<section>
				<h2>Data-driven service optimization</h2>
				<p>
					A single, architected platform for IT Operations Analytics transforms web scale, real-time streaming data, generated by the digital business, into meaningful, actionable insights that fuel fast, business-aligned decisions for IT. To optimize applications and IT-dependent services, the analytics platform must collect and analyze a&nbsp; wide variety of data, including metric, event, log, user experience, IT service management, customer service and sentiment, business and social data, and applying big data analytics in three sequential steps:
				</p>
				<ul>
					<li>
						<b>Data capture and ingestion:</b> real-time streaming, transformation, storage and indexing
					</li>
					<li>
						<b>Analytics and machine learning:</b> automated baselines and abnormality detection, pattern discovery, statistics and probability, recommendation engine
					</li>
					<li>
						<b>Access and explore:</b> visualize, search, correlate and compare, trend, predict and collaborate
					</li>
				</ul>
			</section>

			<section>
				<a class="btn" href="/it-solutions/truesight-intelligence.html"  target="_self">Explore TrueSight Intelligence&nbsp;&#8250;</a>
			</section>

			<blockquote class="testimonial divider">
				<p>
					“In general, the vendor [BMC Software] shines above most of its competitors in realizing the need to combine complex, integrated functionality with ease of deployment and administration.”
				</p>
				<cite> &mdash; Dennis Drogseth, Vice President, Enterprise Management Associates </cite>
				<h5><a href="http://media.cms.bmc.com/documents/EMA-BMC-CaseStudy-Migrating-to-BMC-TrueSight.PDF" target="_blank">Migrating to BMC TrueSight &ndash; A Holistic Answer to Application Service Delivery</a></h5>
			</blockquote>

			<section>
				<h2>Get a complete, end-to-end ITOA solution</h2>

				<h3><a href="/it-solutions/truesight-operations-management.html"  target="_self" >TrueSight Operations Management</a></h3>
				<p>
					BMC TrueSight Operations Management monitors complex IT environments and analyzes diverse data to deliver actionable IT insight that helps you solve business problems.
				</p>

				<h3><a href="/it-solutions/truesight-it-data-analytics.html"  target="_self" >TrueSight IT Data Analytics</a></h3>
				<p>
					BMC TrueSight IT Data Analytics, a key component of TrueSight Operations Management, automatically collects and correlates machine/log data in real time to proactively identify problems and prevent them from recurring.
				</p>

				<h3><a href="/it-solutions/app-visibility-manager.html"  target="_self" >TrueSight AppVisibility</a></h3>
				<p>
					TrueSight AppVisibility is an application performance management suite that monitors and manages packaged, mobile web, web-based and modern application ecosystems, from the infrastructure and code to the customer experience.
				</p>

				<h3><a href="/it-solutions/truesight-infrastructure-management.html"  target="_self" >TrueSight Infrastructure Management</a></h3>
				<p>
					BMC TrueSight Infrastructure Management incorporates network, infrastructure, and data change information and service modeling to offer the earliest, most accurate detection, diagnosis, prioritization, and resolution of service impacts in the industry today.
				</p>
			</section>

			<section>
				<article>
					<h2>Related topics:</h2>
					<dl>

						<dt>

							<a href="/it-solutions/it-operations-management.html"  target="_self" >IT Operations</a>
						</dt>
						<dd>
							BMC's ITOM solutions help you optimize your operations infrastructure with actionable data from monitoring, automation, capacity, and analytics tools.
						</dd>

						<dt>

							<a href="/it-solutions/truesight.html"  target="_self" >TrueSight</a>
						</dt>
						<dd>
							BMC TrueSight performance, availability, and capacity management solutions help you tune your entire IT environment.
						</dd>

						<dt>

							<a href="/it-solutions/application-performance-management.html"  target="_self" >Application Performance Management</a>
						</dt>
						<dd>
							BMC application performance management (APM) solutions deliver deep insight for better, faster decision-making, reduced manual effort for IT staff, and more satisfied business users.
						</dd>
					</dl>
				</article>
			</section>

		</article>

		<aside class="layout-secondary">

			<section>
				<h3>Respond to the big data challenge</h3>
				<figure>
					<a href="/forms/PA-TSIntell-BMCcom-Q2FY16.html" > <img src="http://media.cms.bmc.com/images/form-thumbnail-TSIntellAR_Featured_Asset_Image.png" alt="The Big Data Analytics Reality For Modern Infrastructure And Operations Leaders" title="The Big Data Analytics Reality For Modern Infrastructure And Operations Leaders" width="320"  height="170" border="0"></img> </a>

				</figure>

				<a href="/forms/PA-TSIntell-BMCcom-Q2FY16.html" data-form="" data-location="Secondary-Column"  data-parent-id="368155751" target="_self" >Forrester Research: The Big Data Analytics Reality For Modern Infrastructure And Operations Leaders</a>
			</section>

			<section>

				<figure>
					<a href="/forms/PA-BPPM-ITDataAnalytics-Trial.html?intcmp=td_category_rr_banner"  target="_blank"> <img src="http://media.cms.bmc.com/images/itda-trial-image-2.png" alt="BMC TrueSight IT Data Analytics Free Trial" title="BMC TrueSight IT Data Analytics Free Trial" width="320"  height="266" border="0"></img> </a>

				</figure>
			</section>

			<section>
				<h3>Data-driven decisions</h3>
				<figure>
					<a href="http://documents.bmc.com/products/documents/56/15/465615/465615.pdf"  target="_blank"> <img src="http://media.cms.bmc.com/images/465615_IT_Operations_Analytics_white_paper_0709_Featured_Asset_Image.png" alt="Faster, More Accurate Decisions with IT Operations Analytics" title="Faster, More Accurate Decisions with IT Operations Analytics" width="320"  height="170" border="0"></img> </a>

				</figure>
				<a href="http://documents.bmc.com/products/documents/56/15/465615/465615.pdf" target="_blank">BMC white paper: Faster, More Accurate Decisions with IT Operations Analytics</a>
			</section>

			<section>
				<h3>Analyst perspective</h3>
				<figure>
					<a href="http://media.cms.bmc.com/documents/EMA+Coverage+-+TrueSight+Intelligence+%28September+2015%29.pdf"  target="_blank"> <img src="http://media.cms.bmc.com/images/EMA_Coverage_TrueSight_Intelligence_Featured_Asset_Image.png" alt="BMC Brings Versatility and Ease of Use to Big Data Analytics with TrueSight Intelligence" title="BMC Brings Versatility and Ease of Use to Big Data Analytics with TrueSight Intelligence" width="320"  height="170" border="0"></img> </a>

				</figure>
				<a href="http://media.cms.bmc.com/documents/EMA+Coverage+-+TrueSight+Intelligence+%28September+2015%29.pdf" target="_blank">EMA Impact Brief: BMC Brings Versatility and Ease of Use to Big Data Analytics</a>
			</section>

			<section>
				<h3>Join the conversation</h3>
				Exchange insights in our <a href="https://communities.bmc.com/community/bmcdn/service_assurance/truesight-it-data-analytics">TrueSight IT Data Analytics community</a>
			</section>

			<section>
				<h3>Recent IT Operations blogs</h3>
				<ul class="plain blog-recent">
					<li class="hentry">
						<figure>
							<a href="http://www.bmc.com/blogs/confessions-hacker-protect-enterprise/"> <img src="http://blogs.bmc.com/wp-content/uploads/2017/01/Hack-and-Defend.jpg" alt="Confessions of a “Hacker” and How to Protect Your Enterprise"> </a>
						</figure>
						<div>
							<a class="entry-title" href="http://www.bmc.com/blogs/confessions-hacker-protect-enterprise/"> Confessions of a “Hacker” and How to Protect Your Enterprise </a>
						</div>
					</li>
					<li class="hentry">
						<figure>
							<a href="http://www.bmc.com/blogs/self-service-thrives-clouds/"> <img src="http://blogs.bmc.com/wp-content/uploads/2017/01/Self-Service-IT-Thrives.jpg" alt="Self-Service IT Thrives in the Clouds"> </a>
						</figure>
						<div>
							<a class="entry-title" href="http://www.bmc.com/blogs/self-service-thrives-clouds/"> Self-Service IT Thrives in the Clouds </a>
						</div>
					</li>
					<li class="hentry">
						<figure>
							<a href="http://www.bmc.com/blogs/high-tech-real-time-monitoring-helps-snap-kitchen-keep-stores-stocked-tasty-nutritious-meals/"> <img src="http://blogs.bmc.com/wp-content/uploads/2017/01/Snap-Kitchen.jpg" alt="High-tech Real-Time Monitoring Helps Snap Kitchen Keep Stores Stocked with Tasty, Nutritious Meals"> </a>
						</figure>
						<div>
							<a class="entry-title" href="http://www.bmc.com/blogs/high-tech-real-time-monitoring-helps-snap-kitchen-keep-stores-stocked-tasty-nutritious-meals/"> High-tech Real-Time Monitoring Helps Snap Kitchen Keep Stores Stocked with Tasty, Nutritious Meals </a>
						</div>
					</li>
				</ul>
			</section>

		</aside>
	</div>
</section>

<?php
include 'php-inc/foot.php';
?>