<?php
	$pageTitle = "BMC Pattern Library";
	$bodyClass = "pattern-library";
	include_once 'php-inc/head-pattern-library.php';
?>


	<section class="layout-full-bleed">
		<div id="content-wrapper" class="layout-inner-wrap row">
			
			<section class="item-container">
				<h1>Typography</h1>
				
				<ul class="nav-pagenav">
					<li><a href="#default-headings">Default headings</a></li>
					<li><a href="#typography-example">General typography example</a></li>
				</ul>
				
				<article id="default-headings" class="item">
					<h2>Default heading tags</h2>
					<div class="element-example">
					<?php include 'php-inc/pattern-library/HTML/typography-headings.php' ?>
					</div>
					<div class="row">
						<div class="element-code-preview two-up">

<pre>
<code data-language="html">
<?php include 'php-inc/pattern-library/HTML/typography-headings.php' ?>
</code>
</pre>
						</div>
						<div class="element-notes two-up">
							<p>The typeface we use is <a href="https://www.google.com/fonts/specimen/Open+Sans">Open Sans</a>.</p>
							<p>Some <a href="pattern-library-colors-icons.php#link-icons">icon elements</a> are generated by the use of <a href="https://icomoon.io/#about">Icomoon</a>. 
						</div>
					</div>
				</article>
				
				<article id="typography-example" class="item">
					<h2>General typography example</h2>
					<div class="element-example">
						<?php include 'php-inc/pattern-library/HTML/typography-general.php' ?>
					</div>
					
					<div class="row">
						<div class="element-code-preview two-up">
<pre>
<code data-language="html">						
<?php include 'php-inc/pattern-library/HTML/typography-general.php' ?>
</code>
</pre>
						</div>
						<div class="element-notes two-up">
							<p>Notes regarding General typograhy example</p>
						</div>
					</div>
				</article>
				
			</section>
			
		</div>
	</section>
	

<?php include_once 'php-inc/foot-pattern-library.php'; ?>