export interface Widgets {
    openCase: string,
    listCase: string,
    manageCase:  string,
    docs: string,
    prdDownloads: string,
    askCommunity: string,
    supportVideos: string,
    supportedProducts: string,
    prdCompatibility: string,
    training: string,
    prdSupport: string,
    servicesConsulting : string,
    strategicServices : string,
    bmcHelixServices : string,
    mainframeServices  : string,
    implServices : string,
    managedServices : string,
    enhancedServices  : string
}